"""create phenology stages table

Revision ID: 9ee7ef52969d
Revises: 5a8d7ba87ad7
Create Date: 2025-10-20 10:24:38.238657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee7ef52969d'
down_revision = '5a8d7ba87ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phenology_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.Integer(), nullable=False))
        batch_op.drop_column('days_after_planting')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phenology_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_after_planting', sa.INTEGER(), nullable=False))
        batch_op.drop_column('days')

    # ### end Alembic commands ###
